import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { PasswordEntry, BreachEvent, UpdateRecord, StrengthLevel } from '@/types'

export function generateSecurityReportPDF(report: {
  month: string
  overallScore: number
  strengthDistribution: Record<StrengthLevel, number>
  breachEvents: BreachEvent[]
  updateRecords: UpdateRecord[]
  entries: PasswordEntry[]
}): jsPDF {
  const doc = new jsPDF()

  doc.setFillColor(10, 14, 39)
  doc.rect(0, 0, 210, 297, 'F')

  doc.setTextColor(0, 214, 143)
  doc.setFontSize(24)
  doc.text('SafeVault Security Report', 105, 25, { align: 'center' })

  doc.setTextColor(148, 163, 184)
  doc.setFontSize(12)
  doc.text(report.month, 105, 35, { align: 'center' })

  doc.setTextColor(241, 245, 249)
  doc.setFontSize(16)
  doc.text('Overall Security Score', 20, 55)

  const scoreColor = report.overallScore >= 80 ? [0, 214, 143] : report.overallScore >= 60 ? [255, 165, 2] : [255, 71, 87]
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2])
  doc.setFontSize(36)
  doc.text(`${report.overallScore}`, 20, 75)

  doc.setTextColor(241, 245, 249)
  doc.setFontSize(14)
  doc.text('Strength Distribution', 20, 95)

  const strengthData = [
    ['Very Strong', `${report.strengthDistribution['very-strong'] || 0}`],
    ['Strong', `${report.strengthDistribution['strong'] || 0}`],
    ['Medium', `${report.strengthDistribution['medium'] || 0}`],
    ['Weak', `${report.strengthDistribution['weak'] || 0}`],
  ]

  autoTable(doc, {
    startY: 100,
    head: [['Level', 'Count']],
    body: strengthData,
    theme: 'grid',
    headStyles: { fillColor: [0, 214, 143], textColor: [10, 14, 39] },
    styles: { fillColor: [17, 22, 56], textColor: [241, 245, 249] },
  })

  let currentY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || 140

  if (report.breachEvents.length > 0) {
    const y = currentY + 15
    currentY = y

    doc.setTextColor(255, 71, 87)
    doc.setFontSize(14)
    doc.text('Breach Events', 20, y)

    const breachData = report.breachEvents.map(e => [
      e.website,
      e.source,
      e.breachDate,
      e.resolved ? 'Resolved' : 'Pending',
    ])

    autoTable(doc, {
      startY: y + 5,
      head: [['Website', 'Source', 'Date', 'Status']],
      body: breachData,
      theme: 'grid',
      headStyles: { fillColor: [255, 71, 87], textColor: [255, 255, 255] },
      styles: { fillColor: [17, 22, 56], textColor: [241, 245, 249] },
    })

    currentY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || y + 50
  }

  if (report.updateRecords.length > 0) {
    const y2 = currentY + 15

    doc.setTextColor(59, 130, 246)
    doc.setFontSize(14)
    doc.text('Update Records', 20, y2)

    const updateData = report.updateRecords.map(r => [
      r.website,
      new Date(r.updatedAt).toLocaleDateString('zh-CN'),
    ])

    autoTable(doc, {
      startY: y2 + 5,
      head: [['Website', 'Updated Date']],
      body: updateData,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
      styles: { fillColor: [17, 22, 56], textColor: [241, 245, 249] },
    })
  }

  doc.setTextColor(100, 116, 139)
  doc.setFontSize(8)
  doc.text('Generated by SafeVault - Encrypted & Secure', 105, 290, { align: 'center' })

  return doc
}
